apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: staging-to-core
spec:
  schedule: "*/5 * * * *"   # runs every 5min.
  jobTemplate:
    spec:
      template:
        spec:
          #imagePullSecrets:
          #  - name: my-secrets
          containers:
          - name: staging-to-core
            image: 10.152.183.76:5000/staging-to-core
            env:
              - name: ACCOUNT
                valueFrom:
                  secretKeyRef:
                    name: generated-secret
                    key: account
              - name: REGION
                valueFrom:
                  secretKeyRef:
                    name: generated-secret
                    key: region
              - name: USER
                valueFrom:
                  secretKeyRef:
                    name: generated-secret
                    key: user
              - name: PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: generated-secret
                    key: password
            args: 
              - --context_param context.Core_account=
              - --context_param context.Core_region=
              - --context_param Core_userPassword_userId=jcl
              - --context_param Core_userPassword_password=
          restartPolicy: OnFailure
