apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  # generate a tls Secret
- name: app-tls
  files:
    - certs/server.crt
    - certs/server.key
  type: "kubernetes.io/tls"
- name: env_file_secret
  # you can only specify one env file per secret.
  env: my_secrets_in_clear.txt
  type: Opaque
