replicaCount: 2       # set parent chart values templated as {{ .Values.replicaCount }}

chart-a:
  replicaCount: 3      # set sub chart-a values templated as {{ .Values.replicaCount }}

global:
  replicaCount: 4      # override any chart values templated as {{ .Values.global.replicaCount }}

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
