apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: --skaffold
deploy:
  kubectl:
    manifests:
    - container-configmap.yaml
    - deployment.yaml
    - nginx-deployment.yaml
    - nginx-service.yaml
    - volume-configmap.yaml
profiles:
- name: local-cluster
  activation:
  - env: ENV=local
  - kubeContext: microk8s
    command: dev
- name: dev-cluster
  activation:
  - env: ENV=dev
  - kubeContext: arn:aws:eks:<aws_region>:<aws_account>:cluster/aws_dev
    command: run
