apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
  - image: skaffold-custom
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
        - "go.mod"
        - "**.go"
