apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks
    buildpacks:
      builder: "gcr.io/buildpacks/builder"
      env:
      - GOPROXY={{.GOPROXY}}
    sync:
      auto: {}
profiles:
- name: gcb
  build:
    googleCloudBuild: {}
