---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: chart-a
  annotations:
    flux.weave.works/automated: "true"
spec:
  releasename: chart-a
  chart:
    repository: "http://chartmuseum-chartmuseum:8080"
    name: chart-a
    version: 0.1.0
