---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: chart-c
  annotations:
    flux.weave.works/automated: "true"
spec:
  releasename: chart-c
  chart:
    repository: "http://10.1.1.127:8080"
    name: chart-c
    version: 0.1.0
