dist: xenial

language: go
go: "1.14.x"
go_import_path: /skaffold

git:
  submodules: false

branches:
  only:
    - master

jobs:
  include:
    - os: linux
      name: "linters"
      script:
        - make linters
    - os: linux
      name: "checks"
      script:
        - make checks
      cache:
        directories:
          - $HOME/.cache/go-build
    - os: linux
      name: "Linux unit"
      script:
        - make coverage
      cache:
        directories:
          - $HOME/.cache/go-build
    - os: osx
      name: "OSX unit"
      before_install:
        - curl -Lo ${HOME}/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
        - chmod +x ${HOME}/bin/jq
      script:
        - make quicktest
      cache:
        directories:
          - $HOME/.cache/go-build
    - os: windows
      name: "Windows unit"
      script:
        - go test -short -timeout 60s ./...
      cache:
        directories:
          - C:\\Users\\travis\\AppData\\Local\\go-build
    - os: linux
      name: "integration partition 0"
      language: minimal
      script:
        - env IT_PARTITION=0 make integration-in-kind
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/.gradle
          - $HOME/.m2
    - os: linux
      name: "integration partition 1"
      language: minimal
      script:
        - env IT_PARTITION=1 make integration-in-kind
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/.gradle
          - $HOME/.m2
    - os: linux
      name: "integration partition 2"
      language: minimal
      script:
        - env IT_PARTITION=2 make integration-in-kind
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/.gradle
          - $HOME/.m2
    - os: linux
      name: "integration partition 3"
      language: minimal
      script:
        - env IT_PARTITION=3 make integration-in-kind
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/.gradle
          - $HOME/.m2
    - os: linux
      name: "diag/Linux unit"
      script:
        - make -f Makefile.diag coverage
      cache:
        directories:
          - $HOME/.cache/go-build
    - os: osx
      name: "diag/OSX unit"
      before_install:
        - curl -Lo ${HOME}/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
        - chmod +x ${HOME}/bin/jq
      script:
        - make -f Makefile.diag test
      cache:
        directories:
          - $HOME/.cache/go-build
